// <auto-generated />
using System;
using Beamity.EntityFrameworkCore.EntityFrameworkCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Beamity.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(BeamityDbContext))]
    partial class BeamityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Beamity.Core.Models.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTime");

                    b.Property<bool>("IsActive");

                    b.Property<string>("MainImageURL")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(47);

                    b.Property<int?>("RoomId");

                    b.Property<Guid?>("RoomId1");

                    b.HasKey("Id");

                    b.HasIndex("RoomId1");

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("Beamity.Core.Models.Beacon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTime");

                    b.Property<bool>("IsActive");

                    b.Property<int>("Major");

                    b.Property<int>("Minor");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("UUID")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Beacons");
                });

            modelBuilder.Entity("Beamity.Core.Models.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTime");

                    b.Property<bool>("IsActive");

                    b.Property<int>("LocationId");

                    b.Property<Guid?>("LocationId1");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("LocationId1");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Beamity.Core.Models.Content", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AudioURL");

                    b.Property<DateTime>("CreatedTime");

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsHomePage");

                    b.Property<string>("MainImageURL")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(47);

                    b.Property<string>("SlideImageURL");

                    b.Property<string>("Text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(65);

                    b.Property<string>("VideoURL");

                    b.HasKey("Id");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("Beamity.Core.Models.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BuildingId");

                    b.Property<Guid?>("BuildingId1");

                    b.Property<DateTime>("CreatedTime");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("BuildingId1");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("Beamity.Core.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTime");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Latitude")
                        .IsRequired();

                    b.Property<string>("Longitude")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<Guid?>("ProjectId");

                    b.Property<int>("ProjetId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Beamity.Core.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTime");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Beamity.Core.Models.Relation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ArtifactId");

                    b.Property<Guid?>("ArtifactId1");

                    b.Property<int?>("BeaconId");

                    b.Property<Guid?>("BeaconId1");

                    b.Property<int>("ContentId");

                    b.Property<Guid?>("ContentId1");

                    b.Property<DateTime>("CreatedTime");

                    b.Property<bool>("IsActive");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId1");

                    b.HasIndex("BeaconId1");

                    b.HasIndex("ContentId1");

                    b.ToTable("Relations");
                });

            modelBuilder.Entity("Beamity.Core.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTime");

                    b.Property<int>("FloorId");

                    b.Property<Guid?>("FloorId1");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(47);

                    b.HasKey("Id");

                    b.HasIndex("FloorId1");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Beamity.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTime");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Hash");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Phone");

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.Property<string>("Token");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Beamity.Core.Models.Artifact", b =>
                {
                    b.HasOne("Beamity.Core.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId1");
                });

            modelBuilder.Entity("Beamity.Core.Models.Building", b =>
                {
                    b.HasOne("Beamity.Core.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId1");
                });

            modelBuilder.Entity("Beamity.Core.Models.Floor", b =>
                {
                    b.HasOne("Beamity.Core.Models.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId1");
                });

            modelBuilder.Entity("Beamity.Core.Models.Location", b =>
                {
                    b.HasOne("Beamity.Core.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("Beamity.Core.Models.Relation", b =>
                {
                    b.HasOne("Beamity.Core.Models.Artifact", "Artifact")
                        .WithMany()
                        .HasForeignKey("ArtifactId1");

                    b.HasOne("Beamity.Core.Models.Beacon", "Beacon")
                        .WithMany()
                        .HasForeignKey("BeaconId1");

                    b.HasOne("Beamity.Core.Models.Content", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId1");
                });

            modelBuilder.Entity("Beamity.Core.Models.Room", b =>
                {
                    b.HasOne("Beamity.Core.Models.Floor", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId1");
                });
#pragma warning restore 612, 618
        }
    }
}
